---
apiVersion: v1
kind: Service
metadata:
  name: bcoin
  namespace: default
  labels:
    app: bitcoin-node
    type: bcoin
spec:
  ports:
  - port: 8332
    targetPort: 8332
    name: rpc
  - port: 8333
    targetPort: 8333
    name: mainnet
  selector:
    app: bitcoin-node
    type: bcoin
